### ISSUE TITLE
Making email link work via web form services

### ISSUE THREAD

**Issue by bungabunga** [epidrome/cover-card#14]
I'd like to make the email link on cover-card jekyll theme work not via direct email adress but via some web form (like [Kontactr](https://kontactr.com/)) to stay more anonymous and to better protect myself from spam. This is currently only possible via trick; setting the Kontactr adress as my blog, but then the icon isn't right (see: https://bungabunga.github.io/bungabunga/). Could you possibly enable this option (email icon and custom url field)?

Thanks!

**Comment by epidrome** [comment]
thank you for this idea!

my understanding is that you want an envelope icon and a custom link to an email form service

if the above is correct, then you can you use the custom social media option of the theme and you only need to make local changes at your repository

here is how i used it on my personal card to add a custom link:
https://github.com/epidrome/home/blob/master/_includes/too_social.html
https://github.com/epidrome/home/blob/master/_config.yml

here is a selection of envelope icons:
https://fontawesome.com/icons?d=gallery&q=envelope

**Comment by bungabunga** [comment]
thanks for the tip! with some guessing and trying i managed to do just what i wanted.

**Comment by bungabunga** [comment]
hi, after updating my fork of cover-card the envelope icon suddenly dissapeared. was it something in the recent commits to cover-card that it doesn't work as it used to?

the code under ...master/_includes/too_social.html was
`{% if site.emailform %}
    <li><a class="fa fa-2x fa-envelope" href="{{ site.emailform }}"><span class="description">Email</span></a></li>
    {% endif %}`

and then:
`# Online profiles`

**Comment by epidrome** [comment]
if it is a problem with the cover-card theme, then you can always point your copy to a previous commit of the theme, in order to do so just follow the instructions at the 'Update' section: 
https://github.com/epidrome/cover-card

it sounds more like a problem with font-awesome, usually an icon is gone missing if it is not specified correctly, 

please note that the FA icons are being updated all the time and that cover-card is linked to a particular version of FA and not the latest one:
https://github.com/epidrome/cover-card/blob/master/_includes/head.html

**Comment by bungabunga** [comment]
thanks for your kind advices! will examine.
