### ISSUE TITLE
After the website is deployed, a blank page is displayed.

### ISSUE THREAD

**Issue by kjxbyz** [epidrome/cover-card#37]
[repo](https://github.com/cyf/cyf.github.io)

**Comment by kjxbyz** [comment]
https://chenyifaer.com

After the website is deployed, a blank page is displayed.

**Comment by epidrome** [comment]
@kjxbyz apologies for closing your issue before,

i have not yet investigated it fully, but, a quick solution is to specify the `main` branch in the configuration, [i had to update my home page config too](https://github.com/epidrome/home/blob/master/_config.yml)

my guess is that some upstream (github pages) change has made it necessary to specify branch, because this template repository has two branches main and gh-pages

thus, let's keep this issue open in order to be visible to others too

thank you for reporting this bug!
